run:
    timeout: 5m
    tests: true
    skip-dirs:
        - mocks
        - vendor

linters:
    disable-all: true
    enable:
        - gofmt # Formatação
        - govet # Análise estática padrão
        - gosec # Segurança
        - gocyclo # Complexidade de código
        - ineffassign # Atribuições ineficientes
        - staticcheck # Verificações robustas de lógica
        - godot # Verifica se comentários terminam com ponto (útil para documentação)
        - errcheck # Verifica se erros retornados estão a ser tratados

linters-settings:
    gocyclo:
        min-complexity: 10
    govet:
        check-shadowing: true
